
#=======================================================================================================================
# System properties
#=======================================================================================================================

# Tomcat SSL configuration
server:
  port: 8085


logging:
  #  file: ${spring.application.name}.log
  level.: INFO




